version: "3"
services: 

  base:
    image: postgres:11
    container_name: base
    restart: always
    networks:
      - sales-network
    environment:
      - POSTGRES_DB=base
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123456
    ports:
      - 5432:5432  

networks:
  sales-network:
    driver: bridge